services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_USER: "${DB_USER:-user}"
      POSTGRES_DB: chatsite
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
