services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_USER: "${DB_USER:-user}"
      POSTGRES_DB: chatsite
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    ports:
      - "27017:27017"


volumes:
  db-data:
  mongo-data:
